name: Swift macOS

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.3.app
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-test-discovery -v
